name: Deploy Hello Emad Script

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install dependencies
      run: |
        npm install

    - name: Run helloEmad.js
      run: |
        node hello.js
